<a href="https://colab.research.google.com/github/sreelakshmisajeevan-854/Data-science/blob/main/Assignment2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SECTION A : Data structures and control

1.

In [ ]:
#List of 5 integers
list1=[5,16,3,11,25]
list1

[5, 16, 3, 11, 25]

In [ ]:
#Append 9
list1.append(9)
list1

[5, 16, 3, 11, 25, 9]

In [ ]:
#Extend the list1
list1.extend([31,2,15])
list1

[5, 16, 3, 11, 25, 9, 31, 2, 15]

In [ ]:
#Insert 21 in 3rd position(starting from 0)
list1.insert(3,21)
list1

[5, 16, 3, 21, 11, 25, 9, 31, 2, 15]

In [ ]:
#Remove 11 from list1
list1.remove(11)
list1

[5, 16, 3, 21, 25, 9, 31, 2, 15]

In [ ]:
#Pop
list1.pop()
list1

[5, 16, 3, 21, 25, 9, 31, 2]

In [ ]:
#Clear the list
list1.clear()
list1

[]

In [ ]:
#Index of 24
list2=[44,17,11,9,3,24,11,39,10,11]
list2.index(24)

5

In [ ]:
#Count of 11 in list2
list2.count(11)

3

In [ ]:
#Sort list2
list2.sort()
list2

[3, 9, 10, 11, 11, 11, 17, 24, 39, 44]

In [ ]:
#Reverse list2
list2.reverse()
list2

[44, 39, 24, 17, 11, 11, 11, 10, 9, 3]

2.

In [ ]:
#Tuple with 3 students name
tuple1=('Arya','Manu','Arun')
tuple1

('Arya', 'Manu', 'Arun')

In [ ]:
#Changing the second name in the tuple1
tuple1[1]='Rani' #Tuples are immutable

TypeError: 'tuple' object does not support item assignment

We can't change the element in the tuple since tuples are immutable.

3.


In [ ]:
#Set of integers with duplicate values
set1={2,67,11,5,34,20,5,24}
set1
#Duplicate elements will be ignored since set is an unordered collection of unique elements. Here 5 appears only once in the set1

{2, 5, 11, 20, 24, 34, 67}

4.

In [ ]:
#Dictionary
dict1={'name':'Liya','age':'22','city':'Kochi'}
dict1

{'name': 'Liya', 'age': '22', 'city': 'Kochi'}

In [ ]:
#Update the age and add a new key email
dict1['age']='18'
dict1['email']='Liya123@gmail.com'
dict1

{'name': 'Liya', 'age': '18', 'city': 'Kochi', 'email': 'Liya123@gmail.com'}

5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age=int(input("Enter your age:"))
if age>=18:
  print('You are eligible to vote.')
else:
  print('You are not eligible to vote.')

Enter your age:12
You are not eligible to vote.


6.	Given a 'marks' variable, print the grade

In [ ]:
mark=int(input("Enter your mark: "))
if mark>=90:
  print('Grade : A')
elif mark>=75 and mark<=89:
  print('Grade : B')
elif mark>=50 and mark<=74:
  print('Grade : C')
elif mark<50:
  print('Fail')
else :
  print('Invalid mark')

Enter your mark: 76
Grade : B


7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
num=int(input("Enter a number:"))
if num>0:
  if num%2==0:
    print(num,' is positive and even.')
  else:
    print(num,' is positive but not even.')
elif num==0:
  print(num,' is zero.')
else:
  print(num,' is negative.')

Enter a number:5
5  is positive but not even.


SECTION B : Numpy

8.

In [ ]:
import numpy as np
arr=np.array(5)
arr

array(5)

In [ ]:
#One dimensional array with values 1 to 5
arr_1d=np.array([1,2,3,4,5])
arr_1d

array([1, 2, 3, 4, 5])

In [ ]:
#A 2D array (2x3) with values from 10 to 60 in steps of 10
arr_2d=np.arange(10,70,10).reshape(2,3)
arr_2d

array([[10, 20, 30],
       [40, 50, 60]])

9.


In [ ]:
import numpy as np
arr1=np.random.randint(0,101,(4,4))
arr1

array([[ 1, 70, 26, 37],
       [49, 32, 58, 33],
       [38, 41, 15, 38],
       [26, 64, 40, 91]])

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import pandas as pd
import numpy as np
arr2=np.array([[2,5,8],[3,11,4],[7,1,15]])
df=pd.DataFrame(arr2,columns=['A','B','C'])
df

,A,B,C
0,2,5,8
1,3,11,4
2,7,1,15


Section C: Exploring Pandas

11.


In [ ]:
import pandas as pd
data={
    'Name':['Diya','Manu','Laya','Arun','Jith','Veena','Isha','Fidel','Hina','Diya'],
    'Age':[22,34,32,11,23,45,36,34,18,22],
    'City':['Delhi', 'Mumbai', 'Chennai', 'Kolkata', 'Pune',
             'Hyderabad', 'Bangalore', 'Delhi', 'Mumbai', 'Delhi'],
    'Salary':[35000, 45000, None, 50000, 32000,
               60000, None, 48000, 42000, 35000]
}
df1=pd.DataFrame(data)
df1

,Name,Age,City,Salary
0,Diya,22,Delhi,35000.0
1,Manu,34,Mumbai,45000.0
2,Laya,32,Chennai,NaN
3,Arun,11,Kolkata,50000.0
4,Jith,23,Pune,32000.0
5,Veena,45,Hyderabad,60000.0
6,Isha,36,Bangalore,NaN
7,Fidel,34,Delhi,48000.0
8,Hina,18,Mumbai,42000.0
9,Diya,22,Delhi,35000.0


In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [ ]:
df1.describe()

,Age,Salary
count,10.000000,8.000000
mean,27.700000,43375.000000
std,10.143964,9379.879682
min,11.000000,32000.000000
25%,22.000000,35000.000000
50%,27.500000,43500.000000
75%,34.000000,48500.000000
max,45.000000,60000.000000


In [ ]:
#Select 'Name' and 'City' columns
df1[['Name','City']]

,Name,City
0,Diya,Delhi
1,Manu,Mumbai
2,Laya,Chennai
3,Arun,Kolkata
4,Jith,Pune
5,Veena,Hyderabad
6,Isha,Bangalore
7,Fidel,Delhi
8,Hina,Mumbai


In [ ]:
#Drop 'City' column
df2=df1.drop(['City'],axis=1)
df2

,Name,Age,Salary
0,Diya,22,35000.0
1,Manu,34,45000.0
2,Laya,32,NaN
3,Arun,11,50000.0
4,Jith,23,32000.0
5,Veena,45,60000.0
6,Isha,36,NaN
7,Fidel,34,48000.0
8,Hina,18,42000.0
9,Diya,22,35000.0


In [ ]:
#Fill any missing values in 'Salary' column with the mean
df1['Salary'] = df1['Salary'].fillna(df1['Salary'].mean())
df1
#Salary of Laya and isha filled with mean salary

,Name,Age,City,Salary
0,Diya,22,Delhi,35000.0
1,Manu,34,Mumbai,45000.0
2,Laya,32,Chennai,43375.0
3,Arun,11,Kolkata,50000.0
4,Jith,23,Pune,32000.0
5,Veena,45,Hyderabad,60000.0
6,Isha,36,Bangalore,43375.0
7,Fidel,34,Delhi,48000.0
8,Hina,18,Mumbai,42000.0


In [ ]:
#Remove any duplicate rows
df1.drop_duplicates(inplace=True)
df1
#Removed row 0 and 9

,Name,Age,City,Salary
0,Diya,22,Delhi,35000.0
1,Manu,34,Mumbai,45000.0
2,Laya,32,Chennai,43375.0
3,Arun,11,Kolkata,50000.0
4,Jith,23,Pune,32000.0
5,Veena,45,Hyderabad,60000.0
6,Isha,36,Bangalore,43375.0
7,Fidel,34,Delhi,48000.0
8,Hina,18,Mumbai,42000.0
